export const clinicalAppropriatenessMockData = {
  1056974: {
    mrn: 1056974,
    patientId: 12345678,
    drugBrandedFlag: "No",
    hypersensitivityToIg: "no",
    igaDeficiencyWithAntiIgaAntibodies: "no",
    hypersensitivityToCorn: "no",
    hereditaryIntoleranceToFructose: "no",
    hypersensitivityToHyaluronidase: "no",
    hypersensitivityToHumanAlbumin: "no",
    hyperprolinemia: "no",
    neonateLt3Months: "no",
    gt65YearsOfAge: "no",
    diabetes: "yes",
    renalInsufficencyImpairment: "no",
    cardiacInsufficency: "no",
    pulmonaryInsufficency: "yes",
  },
  1057340: {
    mrn: 1057340,
    patientId: 12345678,
    drugBrandedFlag: "No",
    hypersensitivityToIg: "no",
    igaDeficiencyWithAntiIgaAntibodies: "no",
    hypersensitivityToCorn: "yes",
    hereditaryIntoleranceToFructose: "no",
    hypersensitivityToHyaluronidase: "no",
    hypersensitivityToHumanAlbumin: "yes",
    hyperprolinemia: "no",
    neonateLt3Months: "no",
    gt65YearsOfAge: "no",
    diabetes: "yes",
    renalInsufficencyImpairment: "no",
    cardiacInsufficency: "no",
    pulmonaryInsufficency: "no",
  },
};
