export const financialAssistanceMockData = {
  1056974: {
    InsuranceType: "G",
    INSU_ID: "10598",
    INSU_NM: "01 UHC Community Plan MI",
    PayerName: "UHC Commercial",
    drug_list: [
      {
        IGDTCategory: "PreferSCIG3",
        CategoryPreferredDrug: "Hyqvia",
        NDC: " 0944251102",
        Estimated_margin: "nan",
        ndc_11: "00944251102",
        ClincalContraindication: "Hypersensitivity to Ig",
        Value: "E",
        DXCode: "D80.0",
        MaxAssistance: "50000",
        faDrug: "HyQvia",
        Age: "17",
        Insurance: "C",
        Note: "nan",
      },
      {
        IGDTCategory: "PreferIVIG",
        CategoryPreferredDrug: "Gammaked",
        NDC: "76125090050",
        Estimated_margin: "nan",
        ndc_11: "76125090050",
        ClincalContraindication: "Selective IgA Deficiency",
        Value: "E",
        DXCode: "D69.3",
        MaxAssistance: "2500",
        faDrug: "GAMMAKED",
        Age: "2",
        Insurance: "C",
        Note: "nan",
      },
      {
        IGDTCategory: "PreferSCIG",
        CategoryPreferredDrug: "Cuvitru",
        NDC: "13533081020",
        Estimated_margin: "nan",
        ndc_11: "13533081020",
        ClincalContraindication: "History of Anaphylaxis",
        Value: "E",
        DXCode: "D80.0",
        MaxAssistance: "10000",
        faDrug: "Xembify",
        Age: "2",
        Insurance: "C",
        Note: "nan",
      },
      {
        IGDTCategory: "PreferIVIG3",
        CategoryPreferredDrug: "Octagam 10%",
        NDC: "00069655002",
        Estimated_margin: "nan",
        ndc_11: "00069655002",
        ClincalContraindication: "Renal Impairment",
        Value: "E",
        DXCode: "X",
        MaxAssistance: "12500",
        faDrug: "Octagam Solution 10%",
        Age: "X",
        Insurance: "C",
        Note: "nan",
      },
      {
        IGDTCategory: "PreferIVIG4",
        CategoryPreferredDrug: "Gammaplex 10%",
        NDC: "64208823505",
        Estimated_margin: "nan",
        ndc_11: "64208823505",
        ClincalContraindication: "Hypersensitivity to Ig",
        Value: "E",
        DXCode: "X",
        MaxAssistance: "2000",
        faDrug: "GammaPLEX 10%",
        Age: "X",
        Insurance: "C",
        Note: "nan",
      },
      {
        IGDTCategory: "PreferIVIG2",
        CategoryPreferredDrug: "Octagam 5%",
        NDC: "00069845102",
        Estimated_margin: "nan",
        ndc_11: "00069845102",
        ClincalContraindication: "Hypersensitivity to Ig",
        Value: "E",
        DXCode: "X",
        MaxAssistance: "12500",
        faDrug: "Octagam Solution 5%",
        Age: "X",
        Insurance: "C",
        Note: "nan",
      },
      {
        IGDTCategory: "PreferSCIG3",
        CategoryPreferredDrug: "Hyqvia",
        NDC: " 0944251102",
        Estimated_margin: "nan",
        ndc_11: "00944251102",
        ClincalContraindication: "Secondary Immunodeficiency",
        Value: "E",
        DXCode: "D80.9",
        MaxAssistance: "50000",
        faDrug: "HyQvia",
        Age: "17",
        Insurance: "C",
        Note: "nan",
      },
      {
        IGDTCategory: "PreferIVIG",
        CategoryPreferredDrug: "Gammaked",
        NDC: "76125090050",
        Estimated_margin: "nan",
        ndc_11: "76125090050",
        ClincalContraindication:
          "Chronic Inflammatory Demyelinating Polyneuropathy",
        Value: "E",
        DXCode: "G61.81",
        MaxAssistance: "2500",
        faDrug: "GAMMAKED",
        Age: "2",
        Insurance: "C",
        Note: "nan",
      },
      {
        IGDTCategory: "PreferSCIG",
        CategoryPreferredDrug: "Cuvitru",
        NDC: "13533081020",
        Estimated_margin: "nan",
        ndc_11: "13533081020",
        ClincalContraindication: "Hypersensitivity to Ig",
        Value: "E",
        DXCode: "G11.3",
        MaxAssistance: "10000",
        faDrug: "Xembify",
        Age: "2",
        Insurance: "C",
        Note: "nan",
      },
      {
        IGDTCategory: "PreferSCIG3",
        CategoryPreferredDrug: "Hyqvia",
        NDC: " 0944251102",
        Estimated_margin: "nan",
        ndc_11: "00944251102",
        ClincalContraindication: "Hypersensitivity to Ig",
        Value: "E",
        DXCode: "D80.8",
        MaxAssistance: "50000",
        faDrug: "HyQvia",
        Age: "17",
        Insurance: "C",
        Note: "nan",
      },
      {
        IGDTCategory: "PreferIVIG",
        CategoryPreferredDrug: "Gammaked",
        NDC: "76125090050",
        Estimated_margin: "nan",
        ndc_11: "76125090050",
        ClincalContraindication: "Hypersensitivity to Ig",
        Value: "E",
        DXCode: "D80.9",
        MaxAssistance: "2500",
        faDrug: "GAMMAKED",
        Age: "2",
        Insurance: "C",
        Note: "nan",
      },
      {
        IGDTCategory: "PreferSCIG",
        CategoryPreferredDrug: "Cuvitru",
        NDC: "13533081020",
        Estimated_margin: "nan",
        ndc_11: "13533081020",
        ClincalContraindication: "Hypersensitivity to Ig",
        Value: "E",
        DXCode: "D80.9",
        MaxAssistance: "10000",
        faDrug: "Xembify",
        Age: "2",
        Insurance: "C",
        Note: "nan",
      },
      {
        IGDTCategory: "PreferSCIG3",
        CategoryPreferredDrug: "Hyqvia",
        NDC: " 0944251102",
        Estimated_margin: "nan",
        ndc_11: "00944251102",
        ClincalContraindication: "Hypersensitivity to Ig",
        Value: "E",
        DXCode: "D80.7",
        MaxAssistance: "50000",
        faDrug: "HyQvia",
        Age: "17",
        Insurance: "C",
        Note: "nan",
      },
      {
        IGDTCategory: "PreferIVIG",
        CategoryPreferredDrug: "Gammaked",
        NDC: "76125090050",
        Estimated_margin: "nan",
        ndc_11: "76125090050",
        ClincalContraindication: "Hypersensitivity to Ig",
        Value: "E",
        DXCode: "D80.8",
        MaxAssistance: "2500",
        faDrug: "GAMMAKED",
        Age: "2",
        Insurance: "C",
        Note: "nan",
      },
      {
        IGDTCategory: "PreferSCIG",
        CategoryPreferredDrug: "Cuvitru",
        NDC: "13533081020",
        Estimated_margin: "nan",
        ndc_11: "13533081020",
        ClincalContraindication: "Hypersensitivity to Ig",
        Value: "E",
        DXCode: "D80.8",
        MaxAssistance: "10000",
        faDrug: "Xembify",
        Age: "2",
        Insurance: "C",
        Note: "nan",
      },
      {
        IGDTCategory: "PreferSCIG3",
        CategoryPreferredDrug: "Hyqvia",
        NDC: " 0944251102",
        Estimated_margin: "nan",
        ndc_11: "00944251102",
        ClincalContraindication: "Hypersensitivity to Ig",
        Value: "E",
        DXCode: "D80.6",
        MaxAssistance: "50000",
        faDrug: "HyQvia",
        Age: "17",
        Insurance: "C",
        Note: "nan",
      },
      {
        IGDTCategory: "PreferIVIG",
        CategoryPreferredDrug: "Gammaked",
        NDC: "76125090050",
        Estimated_margin: "nan",
        ndc_11: "76125090050",
        ClincalContraindication: "Hypersensitivity to Ig",
        Value: "E",
        DXCode: "D80.7",
        MaxAssistance: "2500",
        faDrug: "GAMMAKED",
        Age: "2",
        Insurance: "C",
        Note: "nan",
      },
      {
        IGDTCategory: "PreferSCIG",
        CategoryPreferredDrug: "Cuvitru",
        NDC: "13533081020",
        Estimated_margin: "nan",
        ndc_11: "13533081020",
        ClincalContraindication: "Hypersensitivity to Ig",
        Value: "E",
        DXCode: "D80.7",
        MaxAssistance: "10000",
        faDrug: "Xembify",
        Age: "2",
        Insurance: "C",
        Note: "nan",
      },
      {
        IGDTCategory: "PreferSCIG3",
        CategoryPreferredDrug: "Hyqvia",
        NDC: " 0944251102",
        Estimated_margin: "nan",
        ndc_11: "00944251102",
        ClincalContraindication: "Hypersensitivity to Ig",
        Value: "E",
        DXCode: "D80.5",
        MaxAssistance: "50000",
        faDrug: "HyQvia",
        Age: "17",
        Insurance: "C",
        Note: "nan",
      },
    ],
  },

  1057340: {
    InsuranceType: "G",
    INSU_ID: "10598",
    INSU_NM: "01 UHC Community Plan MI",
    PayerName: "UHC Commercial",
    drug_list: [
      {
        IGDTCategory: "PreferIVIG4",
        CategoryPreferredDrug: "Gammaplex 10%",
        NDC: "64208823505",
        Estimated_margin: "nan",
        ndc_11: "64208823505",
        ClincalContraindication: "Hyperprolinemia",
        Value: "A",
        DXCode: "X",
        MaxAssistance: "2000",
        faDrug: "GammaPLEX 10%",
        Age: "X",
        Insurance: "C",
        Note: "nan",
      },
      {
        IGDTCategory: "PreferIVIG2",
        CategoryPreferredDrug: "Octagam 5%",
        NDC: "00069845102",
        Estimated_margin: "nan",
        ndc_11: "00069845102",
        ClincalContraindication: "Sucrose/Isomaltase Deficiency",
        Value: "A",
        DXCode: "X",
        MaxAssistance: "12500",
        faDrug: "Octagam Solution 5%",
        Age: "X",
        Insurance: "C",
        Note: "nan",
      },
      {
        IGDTCategory: "PreferSCIG3",
        CategoryPreferredDrug: "Hyqvia",
        NDC: " 0944251102",
        Estimated_margin: "nan",
        ndc_11: "00944251102",
        ClincalContraindication: "IgA Deficiency with Antibodies",
        Value: "A",
        DXCode: "D80.9",
        MaxAssistance: "50000",
        faDrug: "HyQvia",
        Age: "17",
        Insurance: "C",
        Note: "nan",
      },
      {
        IGDTCategory: "PreferIVIG",
        CategoryPreferredDrug: "Gammaked",
        NDC: "76125090050",
        Estimated_margin: "nan",
        ndc_11: "76125090050",
        ClincalContraindication: "Fluid Overload Risk",
        Value: "A",
        DXCode: "G61.81",
        MaxAssistance: "2500",
        faDrug: "GAMMAKED",
        Age: "2",
        Insurance: "C",
        Note: "nan",
      },
      {
        IGDTCategory: "PreferSCIG",
        CategoryPreferredDrug: "Cuvitru",
        NDC: "13533081020",
        Estimated_margin: "nan",
        ndc_11: "13533081020",
        ClincalContraindication: "Hyperprolinemia",
        Value: "A",
        DXCode: "G11.3",
        MaxAssistance: "10000",
        faDrug: "Xembify",
        Age: "2",
        Insurance: "C",
        Note: "nan",
      },
      {
        IGDTCategory: "PreferSCIG3",
        CategoryPreferredDrug: "Hyqvia",
        NDC: " 0944251102",
        Estimated_margin: "nan",
        ndc_11: "00944251102",
        ClincalContraindication: "Hemolytic Anemia",
        Value: "A",
        DXCode: "D80.8",
        MaxAssistance: "50000",
        faDrug: "HyQvia",
        Age: "17",
        Insurance: "C",
        Note: "nan",
      },
      {
        IGDTCategory: "PreferIVIG",
        CategoryPreferredDrug: "Gammaked",
        NDC: "76125090050",
        Estimated_margin: "nan",
        ndc_11: "76125090050",
        ClincalContraindication: "Aseptic Meningitis Syndrome",
        Value: "A",
        DXCode: "D80.9",
        MaxAssistance: "2500",
        faDrug: "GAMMAKED",
        Age: "2",
        Insurance: "C",
        Note: "nan",
      },
      {
        IGDTCategory: "PreferSCIG",
        CategoryPreferredDrug: "Cuvitru",
        NDC: "13533081020",
        Estimated_margin: "nan",
        ndc_11: "13533081020",
        ClincalContraindication: "Hyperprolinemia",
        Value: "A",
        DXCode: "D80.9",
        MaxAssistance: "10000",
        faDrug: "Xembify",
        Age: "2",
        Insurance: "C",
        Note: "nan",
      },
      {
        IGDTCategory: "PreferSCIG3",
        CategoryPreferredDrug: "Hyqvia",
        NDC: " 0944251102",
        Estimated_margin: "nan",
        ndc_11: "00944251102",
        ClincalContraindication: "Hyperprolinemia",
        Value: "A",
        DXCode: "D80.7",
        MaxAssistance: "50000",
        faDrug: "HyQvia",
        Age: "17",
        Insurance: "C",
        Note: "nan",
      },
      {
        IGDTCategory: "PreferIVIG",
        CategoryPreferredDrug: "Gammaked",
        NDC: "76125090050",
        Estimated_margin: "nan",
        ndc_11: "76125090050",
        ClincalContraindication: "Hyperprolinemia",
        Value: "A",
        DXCode: "D80.8",
        MaxAssistance: "2500",
        faDrug: "GAMMAKED",
        Age: "2",
        Insurance: "C",
        Note: "nan",
      },
      {
        IGDTCategory: "PreferSCIG",
        CategoryPreferredDrug: "Cuvitru",
        NDC: "13533081020",
        Estimated_margin: "nan",
        ndc_11: "13533081020",
        ClincalContraindication: "Hyperprolinemia",
        Value: "A",
        DXCode: "D80.8",
        MaxAssistance: "10000",
        faDrug: "Xembify",
        Age: "2",
        Insurance: "C",
        Note: "nan",
      },
      {
        IGDTCategory: "PreferSCIG3",
        CategoryPreferredDrug: "Hyqvia",
        NDC: " 0944251102",
        Estimated_margin: "nan",
        ndc_11: "00944251102",
        ClincalContraindication: "Hyperprolinemia",
        Value: "A",
        DXCode: "D80.6",
        MaxAssistance: "50000",
        faDrug: "HyQvia",
        Age: "17",
        Insurance: "C",
        Note: "nan",
      },
      {
        IGDTCategory: "PreferIVIG",
        CategoryPreferredDrug: "Gammaked",
        NDC: "76125090050",
        Estimated_margin: "nan",
        ndc_11: "76125090050",
        ClincalContraindication: "Hyperprolinemia",
        Value: "A",
        DXCode: "D80.7",
        MaxAssistance: "2500",
        faDrug: "GAMMAKED",
        Age: "2",
        Insurance: "C",
        Note: "nan",
      },
      {
        IGDTCategory: "PreferSCIG",
        CategoryPreferredDrug: "Cuvitru",
        NDC: "13533081020",
        Estimated_margin: "nan",
        ndc_11: "13533081020",
        ClincalContraindication: "Hyperprolinemia",
        Value: "A",
        DXCode: "D80.7",
        MaxAssistance: "10000",
        faDrug: "Xembify",
        Age: "2",
        Insurance: "C",
        Note: "nan",
      },
      {
        IGDTCategory: "PreferSCIG3",
        CategoryPreferredDrug: "Hyqvia",
        NDC: " 0944251102",
        Estimated_margin: "nan",
        ndc_11: "00944251102",
        ClincalContraindication: "Hyperprolinemia",
        Value: "A",
        DXCode: "D80.5",
        MaxAssistance: "50000",
        faDrug: "HyQvia",
        Age: "17",
        Insurance: "C",
        Note: "nan",
      },
      {
        IGDTCategory: "PreferIVIG",
        CategoryPreferredDrug: "Gammaked",
        NDC: "76125090050",
        Estimated_margin: "nan",
        ndc_11: "76125090050",
        ClincalContraindication: "Hyperprolinemia",
        Value: "A",
        DXCode: "D80.6",
        MaxAssistance: "2500",
        faDrug: "GAMMAKED",
        Age: "2",
        Insurance: "C",
        Note: "nan",
      },
      {
        IGDTCategory: "PreferSCIG",
        CategoryPreferredDrug: "Cuvitru",
        NDC: "13533081020",
        Estimated_margin: "nan",
        ndc_11: "13533081020",
        ClincalContraindication: "Hyperprolinemia",
        Value: "A",
        DXCode: "D80.6",
        MaxAssistance: "10000",
        faDrug: "Xembify",
        Age: "2",
        Insurance: "C",
        Note: "nan",
      },
    ],
  },
};
