export const payorCostMockData = {
  1056974: {
    payors: [
      {
        name: "*NATIONAL: Cigna ALL SITES 02/01/21",
        items: [
          {
            cleanDrug: "Skilled Nursing Additional - 99602",
            hcpc: "99602",
            costGram: 0.0,
            expectedGram: 70.0,
          },
          {
            cleanDrug: "Skilled Nursing Initial 2hrs-99601",
            hcpc: "99601",
            costGram: 0.0,
            expectedGram: 140.0,
          },
          {
            cleanDrug: "Bivigam",
            hcpc: "J1556",
            costGram: 137.67,
            expectedGram: 157.62,
          },
          {
            cleanDrug: "CutaQUIG",
            hcpc: "J1551",
            costGram: 133.44,
            expectedGram: 151.6,
          },
          {
            cleanDrug: "Gammagard Liquid",
            hcpc: "J1569",
            costGram: 91.54,
            expectedGram: 117.99,
          },
          {
            cleanDrug: "Xembify",
            hcpc: "J1558",
            costGram: 129.51,
            expectedGram: 142.29,
          },
          {
            cleanDrug: "Bivigam",
            hcpc: "J1556",
            costGram: 137.67,
            expectedGram: 157.61,
          },
          {
            cleanDrug: "Cytogam",
            hcpc: "J0850",
            costGram: 702.55,
            expectedGram: 0.08,
          },
          {
            cleanDrug: "GamuNEX-C",
            hcpc: "J1561",
            costGram: 102.84,
            expectedGram: 110.57,
          },
          {
            cleanDrug: "Privigen",
            hcpc: "J1459",
            costGram: 94.02,
            expectedGram: 130.35,
          },
          {
            cleanDrug: "GammaKED",
            hcpc: "J1561",
            costGram: 101.69,
            expectedGram: 148.37,
          },
          {
            cleanDrug: "CuvITRU",
            hcpc: "J1555",
            costGram: 152.47,
            expectedGram: 188.56,
          },
          {
            cleanDrug: "GammaPLEX 5%*",
            hcpc: "J1557",
            costGram: 101.07,
            expectedGram: 153.83,
          },
          {
            cleanDrug: "CutaQUIG",
            hcpc: "J1551",
            costGram: 133.44,
            expectedGram: 160.04,
          },
          {
            cleanDrug: "CuvITRU",
            hcpc: "J1555",
            costGram: 152.47,
            expectedGram: 188.55,
          },
          {
            cleanDrug: "Octagam 5%*",
            hcpc: "J1568",
            costGram: 87.59,
            expectedGram: 125.88,
          },
          {
            cleanDrug: "Hizentra",
            hcpc: "J1559",
            costGram: 118.23,
            expectedGram: 163.72,
          },
          {
            cleanDrug: "Gammagard Liquid",
            hcpc: "J1569",
            costGram: 91.54,
            expectedGram: 117.98,
          },
          {
            cleanDrug: "HyQvia",
            hcpc: "J1575",
            costGram: 172.05,
            expectedGram: 191.39,
          },
          {
            cleanDrug: "Gammagard Less IgA",
            hcpc: "J1566",
            costGram: 146.02,
            expectedGram: 161.47,
          },
          {
            cleanDrug: "Asceniv",
            hcpc: "J1554",
            costGram: 927.18,
            expectedGram: 1012.87,
          },
          {
            cleanDrug: "Octagam 5%*",
            hcpc: "J1568",
            costGram: 87.59,
            expectedGram: 125.87,
          },
          {
            cleanDrug: "Per Diem IVIG",
            hcpc: "S9338",
            costGram: 0.0,
            expectedGram: 70.0,
          },
          {
            cleanDrug: "Per Diem SCIG",
            hcpc: "S9338",
            costGram: 0.0,
            expectedGram: 70.0,
          },
        ],
      },
      {
        name: "*NATIONAL: UHC ALL Sites ppoOne",
        items: [
          {
            cleanDrug: "Skilled Nursing Additional - 99602",
            hcpc: "99602",
            costGram: 0.0,
            expectedGram: 65.0,
          },
          {
            cleanDrug: "Skilled Nursing Initial 2hrs-99601",
            hcpc: "99601",
            costGram: 0.0,
            expectedGram: 130.0,
          },
          {
            cleanDrug: "Bivigam",
            hcpc: "J1556",
            costGram: 137.67,
            expectedGram: 134.85,
          },
          {
            cleanDrug: "Cytogam",
            hcpc: "J0850",
            costGram: 702.55,
            expectedGram: 440.87,
          },
          {
            cleanDrug: "CutaQUIG",
            hcpc: "J1551",
            costGram: 133.44,
            expectedGram: 209.29,
          },
          {
            cleanDrug: "GammaPLEX 5%*",
            hcpc: "J1557",
            costGram: 101.07,
            expectedGram: 128.19,
          },
          {
            cleanDrug: "Asceniv",
            hcpc: "J1554",
            costGram: 927.18,
            expectedGram: 0.0,
          },
          {
            cleanDrug: "CutaQUIG",
            hcpc: "J1551",
            costGram: 133.44,
            expectedGram: 209.28,
          },
          {
            cleanDrug: "Xembify",
            hcpc: "J1558",
            costGram: 129.51,
            expectedGram: 153.23,
          },
          {
            cleanDrug: "HyQvia",
            hcpc: "J1575",
            costGram: 172.05,
            expectedGram: 206.82,
          },
          {
            cleanDrug: "CuvITRU",
            hcpc: "J1555",
            costGram: 152.47,
            expectedGram: 185.86,
          },
          {
            cleanDrug: "GamuNEX-C",
            hcpc: "J1561",
            color: "#64748b",
            costGram: 102.84,
            expectedGram: 113.97,
          },
          {
            cleanDrug: "Cytogam",
            hcpc: "J0850",
            costGram: 702.55,
            expectedGram: 522.84,
          },
          {
            cleanDrug: "Octagam 5%*",
            hcpc: "J1568",
            costGram: 87.59,
            expectedGram: 116.55,
          },
          {
            cleanDrug: "CutaQUIG",
            hcpc: "J1551",
            costGram: 133.44,
            expectedGram: 198.25,
          },
          {
            cleanDrug: "GammaKED",
            hcpc: "J1561",
            costGram: 101.69,
            expectedGram: 141.31,
          },
          {
            cleanDrug: "Privigen",
            hcpc: "J1459",
            costGram: 94.02,
            expectedGram: 121.66,
          },
          {
            cleanDrug: "Gammagard Liquid",
            hcpc: "J1569",
            costGram: 91.54,
            expectedGram: 115.95,
          },
          {
            cleanDrug: "Hizentra",
            hcpc: "J1559",
            costGram: 118.23,
            expectedGram: 133.71,
          },
          {
            cleanDrug: "Gammagard Less IgA",
            hcpc: "J1566",
            costGram: 146.02,
            expectedGram: 156.08,
          },
          {
            cleanDrug: "Per Diem IVIG",
            hcpc: "S9338",
            costGram: 0.0,
            expectedGram: 75.0,
          },
          {
            cleanDrug: "Per Diem SCIG",
            hcpc: "S9338",
            costGram: 0.0,
            expectedGram: 75.0,
          },
        ],
      },
    ],
    uniquePayors: [
      "*NATIONAL: Cigna ALL SITES 02/01/21",
      "*NATIONAL: UHC ALL Sites ppoOne",
    ],
  },
  1057340: {
    payors: [
      {
        name: "*NATIONAL: Cigna ALL SITES 02/01/21",
        items: [
          {
            cleanDrug: "Skilled Nursing Additional - 99602",
            hcpc: "99602",
            costGram: 0.0,
            expectedGram: 70.0,
          },
          {
            cleanDrug: "Skilled Nursing Initial 2hrs-99601",
            hcpc: "99601",
            costGram: 0.0,
            expectedGram: 140.0,
          },
          {
            cleanDrug: "Bivigam",
            hcpc: "J1556",
            costGram: 137.67,
            expectedGram: 157.62,
          },
          {
            cleanDrug: "CutaQUIG",
            hcpc: "J1551",
            costGram: 133.44,
            expectedGram: 151.6,
          },
          {
            cleanDrug: "Gammagard Liquid",
            hcpc: "J1569",
            costGram: 91.54,
            expectedGram: 117.99,
          },
          {
            cleanDrug: "Xembify",
            hcpc: "J1558",
            costGram: 129.51,
            expectedGram: 142.29,
          },
          {
            cleanDrug: "Bivigam",
            hcpc: "J1556",
            costGram: 137.67,
            expectedGram: 157.61,
          },
          {
            cleanDrug: "Cytogam",
            hcpc: "J0850",
            costGram: 702.55,
            expectedGram: 0.08,
          },
          {
            cleanDrug: "GamuNEX-C",
            hcpc: "J1561",
            costGram: 102.84,
            expectedGram: 110.57,
          },
          {
            cleanDrug: "Privigen",
            hcpc: "J1459",
            costGram: 94.02,
            expectedGram: 130.35,
          },
          {
            cleanDrug: "GammaKED",
            hcpc: "J1561",
            costGram: 101.69,
            expectedGram: 148.37,
          },
          {
            cleanDrug: "CuvITRU",
            hcpc: "J1555",
            costGram: 152.47,
            expectedGram: 188.56,
          },
          {
            cleanDrug: "GammaPLEX 5%*",
            hcpc: "J1557",
            costGram: 101.07,
            expectedGram: 153.83,
          },
          {
            cleanDrug: "CutaQUIG",
            hcpc: "J1551",
            costGram: 133.44,
            expectedGram: 160.04,
          },
          {
            cleanDrug: "CuvITRU",
            hcpc: "J1555",
            costGram: 152.47,
            expectedGram: 188.55,
          },
          {
            cleanDrug: "Octagam 5%*",
            hcpc: "J1568",
            costGram: 87.59,
            expectedGram: 125.88,
          },
          {
            cleanDrug: "Hizentra",
            hcpc: "J1559",
            costGram: 118.23,
            expectedGram: 163.72,
          },
          {
            cleanDrug: "Gammagard Liquid",
            hcpc: "J1569",
            costGram: 91.54,
            expectedGram: 117.98,
          },
          {
            cleanDrug: "HyQvia",
            hcpc: "J1575",
            costGram: 172.05,
            expectedGram: 191.39,
          },
          {
            cleanDrug: "Gammagard Less IgA",
            hcpc: "J1566",
            costGram: 146.02,
            expectedGram: 161.47,
          },
          {
            cleanDrug: "Asceniv",
            hcpc: "J1554",
            costGram: 927.18,
            expectedGram: 1012.87,
          },
          {
            cleanDrug: "Octagam 5%*",
            hcpc: "J1568",
            costGram: 87.59,
            expectedGram: 125.87,
          },
          {
            cleanDrug: "Per Diem IVIG",
            hcpc: "S9338",
            costGram: 0.0,
            expectedGram: 70.0,
          },
          {
            cleanDrug: "Per Diem SCIG",
            hcpc: "S9338",
            costGram: 0.0,
            expectedGram: 70.0,
          },
        ],
      },
      {
        name: "*NATIONAL: UHC ALL Sites ppoOne",
        items: [
          {
            cleanDrug: "Skilled Nursing Additional - 99602",
            hcpc: "99602",
            costGram: 0.0,
            expectedGram: 65.0,
          },
          {
            cleanDrug: "Skilled Nursing Initial 2hrs-99601",
            hcpc: "99601",
            costGram: 0.0,
            expectedGram: 130.0,
          },
          {
            cleanDrug: "Bivigam",
            hcpc: "J1556",
            costGram: 137.67,
            expectedGram: 134.85,
          },
          {
            cleanDrug: "Cytogam",
            hcpc: "J0850",
            costGram: 702.55,
            expectedGram: 440.87,
          },
          {
            cleanDrug: "CutaQUIG",
            hcpc: "J1551",
            costGram: 133.44,
            expectedGram: 209.29,
          },
          {
            cleanDrug: "GammaPLEX 5%*",
            hcpc: "J1557",
            costGram: 101.07,
            expectedGram: 128.19,
          },
          {
            cleanDrug: "Asceniv",
            hcpc: "J1554",
            costGram: 927.18,
            expectedGram: 0.0,
          },
          {
            cleanDrug: "CutaQUIG",
            hcpc: "J1551",
            costGram: 133.44,
            expectedGram: 209.28,
          },
          {
            cleanDrug: "Xembify",
            hcpc: "J1558",
            costGram: 129.51,
            expectedGram: 153.23,
          },
          {
            cleanDrug: "HyQvia",
            hcpc: "J1575",
            costGram: 172.05,
            expectedGram: 206.82,
          },
          {
            cleanDrug: "CuvITRU",
            hcpc: "J1555",
            costGram: 152.47,
            expectedGram: 185.86,
          },
          {
            cleanDrug: "GamuNEX-C",
            hcpc: "J1561",
            color: "#64748b",
            costGram: 102.84,
            expectedGram: 113.97,
          },
          {
            cleanDrug: "Cytogam",
            hcpc: "J0850",
            costGram: 702.55,
            expectedGram: 522.84,
          },
          {
            cleanDrug: "Octagam 5%*",
            hcpc: "J1568",
            costGram: 87.59,
            expectedGram: 116.55,
          },
          {
            cleanDrug: "CutaQUIG",
            hcpc: "J1551",
            costGram: 133.44,
            expectedGram: 198.25,
          },
          {
            cleanDrug: "GammaKED",
            hcpc: "J1561",
            costGram: 101.69,
            expectedGram: 141.31,
          },
          {
            cleanDrug: "Privigen",
            hcpc: "J1459",
            costGram: 94.02,
            expectedGram: 121.66,
          },
          {
            cleanDrug: "Gammagard Liquid",
            hcpc: "J1569",
            costGram: 91.54,
            expectedGram: 115.95,
          },
          {
            cleanDrug: "Hizentra",
            hcpc: "J1559",
            costGram: 118.23,
            expectedGram: 133.71,
          },
          {
            cleanDrug: "Gammagard Less IgA",
            hcpc: "J1566",
            costGram: 146.02,
            expectedGram: 156.08,
          },
          {
            cleanDrug: "Per Diem IVIG",
            hcpc: "S9338",
            costGram: 0.0,
            expectedGram: 75.0,
          },
          {
            cleanDrug: "Per Diem SCIG",
            hcpc: "S9338",
            costGram: 0.0,
            expectedGram: 75.0,
          },
        ],
      },
    ],
    uniquePayors: [
      "*NATIONAL: Cigna ALL SITES 02/01/21",
      "*NATIONAL: UHC ALL Sites ppoOne",
    ],
  },
};
